# GenAI Toolkit Configuration
# Basic configuration for running tests, Agents and CLI commands

# Default configuration, as defined in baseline.yaml, overrides.yaml (here), or elsewhere.
# It can be overidden by 'BLUEPRINT_CONFIG' environment variable, or in code

default_config: ${oc.env:BLUEPRINT_CONFIG,baseline}


paths:
  home: ${oc.env:HOME}
  project: ${oc.env:PWD}
  config: ${paths.project}/config/basic
  data_root: ${paths.project}/data

merge:
  - ${paths.config}/init/baseline.yaml
  - ${paths.config}/init/overrides.yaml
  - ${paths.config}/init/mcp_servers.yaml
 

# Command Line Interface configuration
cli:
  commands:  # List modules:functions to register CLI commands
    - genai_tk.core.commands_core:register_commands
    - genai_tk.extra.commands_extra:register_commands
    - genai_tk.extra.agents.commands_agents:register_commands
    - genai_tk.extra.rag.commands_rag:register_commands
    - genai_tk.main.cli:register_commands

# Logging configuration
logging:
  level: "INFO"
