mcpServers:
  filesystem:
      command: npx
      args: 
      - "-y"
      - "@modelcontextprotocol/server-filesystem"
      - ${paths.project}

  playwright:
    command: npx
    args: 
    - "@playwright/mcp@latest"
    - "--headless"

  playwright_ui:  # Does not seems to work in headed mode (in WSL...)
    command: npx
    args: 
    - "@playwright/mcp@latest"

  tavily-mcp: 
    command: npx
    args: [ "-y" ,"tavily-mcp"]
    env: 
      TAVILY_API_KEY : ${oc.env:TAVILY_API_KEY,  "dummy key"}

  github:
    command: npx
    args:  ["-y", "@modelcontextprotocol/server-github"]
    env:
      GITHUB_PERSONAL_ACCESS_TOKEN: ${oc.env:GITHUB_TOKEN_, "dummy token"}
    disabled: true

  pubmed:
      command: uvx
      args: ["--quiet", "pubmedmcp@0.1.3"]
      description: Provides access to PubMed medical research database
      example : "Find relevant studies on alcohol hangover and treatment."
      disabled: true
