# Pytest-specific configuration
pytest:
  # Use  for pytest
  llm:
    models:
      default: parrot_local_fake
      fake: parrot_local_fake
      test: gpt_41mini_openai
  embeddings:
    models:
      default: embeddings_768@fake
      fake: embeddings_768@fake
      test: ada-002@openai
  kv_store:
    engine: "memory"
  llm_cache:
    method: "memory"
  logging:
    level: "INFO"
  paths:
    models: data/models  # Models directory for testing
  vector_store:
    postgres_url: null  # No postgres for tests
